http:
  port: 3005
  cors:
    allowOrigins: ['*']  
    allowMethods: ['GET', 'POST', 'PUT', 'DELETE'] 
    allowHeaders: ['Content-Type', 'Authorization'] 
apiEndpoints:
  apiDeals:
    host: '*'
    paths: '/deal/*'
  apiConveyor:
    host: '*'
    paths: '/conveyor/*'
serviceEndpoints:
  apiDealsService:
    url: 'http://api-deals:3002'
  apiConveyorService:
    url: 'http://api-conveyer:3001'
policies:
  - proxy
pipelines:
  apiDeals:
    apiEndpoints:
      - apiDeals
    policies:
      - proxy:
          action:
            serviceEndpoint: apiDealsService
            changeOrigin: true
  apiConveyor:
    apiEndpoints:
      - apiConveyor
    policies:
      - proxy:
          action:
            serviceEndpoint: apiConveyorService
            changeOrigin: true
